services:
    nginx:
        image: nginx:latest
        container_name: reservation_management_nginx
        restart: unless-stopped
        depends_on:
            - app
            - mysql
        ports:
            - "${APP_PORT:-80}:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/log:/var/log/nginx
            - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - localhost-network

    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: reservation_management_app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - localhost-network

    mysql:
        image: "mysql/mysql-server:8.0"
        restart: unless-stopped
        container_name: reservation_management_mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - localhost-network

networks:
    localhost-network:
        driver: bridge
